version: '3.8'
networks:
  echecs:

services:
  smtp:
    container_name: echecs_fakesmtp
    image: 'munkyboy/fakesmtp'
    networks:
      - echecs

  db:
    container_name: echecs_db
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=SuperPassword
      - POSTGRES_USER=Moi
      - POSTGRES_DB=echecs
    networks:
      - echecs

  backend:
    container_name: echecs_api
    #build: ../TournoiEchecs
    # amd
    image: 'ylorthpro/tournoi-echecs:latest'
    # arm
    # image: 'ylorthpro/tournoi-echecs-arm:latest'
    ports:
      - '8080:8080'
    depends_on:
      - db
      - smtp
    networks:
      - echecs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=echecs
      - POSTGRES_USERNAME=Moi
      - POSTGRES_PASSWORD=SuperPassword
      - MAIL_HOST=smtp
      - MAIL_PORT=25
